# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://yuanzhi-zhu.github.io
date_format: "ordinal"
title: Yuanzhi Zhu
subtitle: "It is never too LAZY to learn"
description: "It is never too LAZY to learn"
keywords: Yuanzhi Zhu
timezone: Europe/Berlin
encoding: "utf-8"
side_bar_repo_limit: 3

# ---------------- #
#      Author      #
# ---------------- #
author: Yuanzhi Zhu
organization: 
organization_url: 
github_username: yuanzhi-zhu
location: Zürich, Switzerland
email: yuazhu@student.ethz.ch

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

#  -
#    href: /categories/
#    label: Category

#   -
#     href: /archives/
#     label: 归档

#  -
#    href: /wiki/
#    label: Wiki

#  -
#    href: /links/
#    label: Links

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 6
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
#collections:
#    wiki:
#        output: true
#        permalink: /wiki/:path/

repository: yuanzhi-zhu/yuanzhi-zhu.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk

# !!!Important!!! Please modify infos below to yours
# https://disqus.com
#disqus:
#    username: 
## https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: mzlogin
#    repo: blog-comments
#    oauth:
#        client_id: d2e1cbbd298958076462
#        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: yuanzhi-zhu
    repo: yuanzhi-zhu
    clientID: 7fdcca9624f082f2fd1e
    clientSecret: 7408a6bc70b766c85f3eaff22433262e00c848e2
# when using other support providers you can display Disqus be click
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # fulltext search support
    fulltext: true
    # maximum search result
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
#    analytics_id: UA-80669434-1
