# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://yuanzhi-zhu.github.io
date_format: "ordinal"
title: Yuanzhi Zhu
subtitle: "It is never too LAZY to learn"
# description: "It is never too LAZY to learn"
keywords: Yuanzhi Zhu
timezone: Europe/Berlin
encoding: "utf-8"
side_bar_repo_limit: 3

# ---------------- #
#      Author      #
# ---------------- #
author: Yuanzhi Zhu
organization: 
organization_url: 
github_username: yuanzhi-zhu
location: Zürich, Switzerland
# email: yuazhu@student.ethz.ch

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Blog

#   -
#     href: /archives/
#     label: Archives

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 6
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
#collections:
#    wiki:
#        output: true
#        permalink: /wiki/:path/

repository: yuanzhi-zhu/yuanzhi-zhu.github.io


# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # fulltext search support
    fulltext: true
    # maximum search result
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
#    analytics_id: UA-80669434-1
